language: node_js
node_js:
  - '0.12'
before_install:
  - 'npm install -g bower grunt-cli'
before_script:
  - mkdir -p '/logs'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script:
  - 'npm test'
  - 'npm run coveralls'
  - 'npm run saucelabs'
after_script:
  - 'cat /logs/karma.log'
env:
  global:
    - secure: L+EPka9O38GaLwg3xqr6p9rwvwy4MnQH0Fba8Qlt1M5QzLRz3e9JdVvxCQrQlETR5Guc5CN1dLOQFhVyYoCFNcOs3VkeD/mnegq16LwFE9vcmxySRqleUja3eCQ4HQJP99pSiCHYQVGvoZUf82nYNz6bh7JusbGapyyUF4Nl1TU=
    - secure: l7fKnvanXbaLGAhlwyFRgNsSy8H5O13nbAU1AujLy9sP5tHnjHjvNLklV+wHw929h2L3pLi0OCMthDQPyA+4LnTNix6UW2f7p1tOwAxOqEWUSitWHway1pNOR9CZbpGVfdcoML/RGNgt1iwtEC9TyhxhbFw1pGZj8GLfCOVdthk=
addons:
  sauce_connect: true
